sudo: false

language: python

python:
  - 2.7

install:
  - pip2 install python2
  - pip2 install requests==2.5.3
  - pip2 install rsa
  - pip2 install thrift==0.9.3
  - pip2 install bs4
  - pip2 install gtts
  - pip2 install googletrans
  - pip2 install beautifulsoup
  
  
script:
  - python2 cmg.py

after_success:
  - python2
